spring:
  application:
    name: configServer1
  cloud:
    config:
      server:
        git:
          uri: https://github.com/feiniao168/sc-config  # 远程git仓库的地址
          username: feiniao168  # 以及相应的账户名
          password: feiniao@2008  # 和密码
          basedir: D:\springcloud-demo\sc-config  # 可以使用这个配置项来指定本地git仓库的路径
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 7001